const CHANGE_MODAL = "CHANGE_MODAL"
const CHANGE_SCORE = "CHANGE_SCORE"
const NEW_QUESTION = "NEW_QUESTION"
const CHOOSE_OPTION = "CHOOSE_OPTION"
const VISIT_OPTION = "VISIT_OPTION"

export  {
    CHANGE_MODAL,
    NEW_QUESTION,
    CHOOSE_OPTION,
    CHANGE_SCORE,
    VISIT_OPTION
}